### ISSUE TITLE
Video from record freeze after few minute in https protocol

### ISSUE THREAD

**Issue by anusornleo** [AgoraIO/Basic-Recording#45]
I use a docker to run this project and user nginx as a web server in project. I make a docker-compose file in dev mode and production mode

This is docker-compose and nginx config for my recorder(run port 4000)

**docker-compose file Dev mode run as http protocol**
```
...
other code
...
recorder:  // my node recorder
    container_name: "recorder-project"
    build:
      context: ./recorder
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    command: >
      sh -c "tail -f /dev/null"
    volumes:
      - ./recorder:/recorder:Z
      - ./record_volume:/usr/src/recorder/output

nginx:
  container_name: nginx-project
    build:
      context: ./nginx
      dockerfile: Dockerfile    // dockerfile in nginx
    volumes:
      - ./media_volume:/uploads
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend     // my frontend
      - backend     // my backend
      - recorder     // recorder in nodejs
```

**docker-compose file Production Mode run as https protocal**
```
...
other code
...
recorder:  // my node recorder
    container_name: "recorder-project"
    build:
      context: ./recorder
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    command: >
      sh -c "tail -f /dev/null"
    volumes:
      - ./recorder:/recorder:Z
      - ./record_volume:/usr/src/recorder/output

nginx-ssl:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: '127.0.0.1'
      SITES: '127.0.0.1=nginx:80'

nginx:
    container_name: nginx-homepro-live
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
      - recorder
```

**Nginx config (use this config both mode)**
```
... other code ...
upstream recorder {
  server recorder:4000;
  keepalive 9;
}
server {
  client_max_body_size 20M;
  listen 80;

... other code ...

  location /recorder/ {
    proxy_pass http://recorder;
    proxy_redirect off;
    proxy_connect_timeout       6000;
    proxy_send_timeout          6000;
    proxy_read_timeout          6000;
    send_timeout                6000;
  }
}
```

When I run my project in dev mode (docker-compose file Dev mode).Then start to broadcast streaming and call api to start record. After stop record. The Result of video can watch normally (not freeze). But when I run in Production Mode (docker-compose file Production Mode) and start record broadcast streaming. It will freeze in 10s to 2 minute.For example of result https://drive.google.com/file/d/1jehoPCvoOxgFbkGiIy22_9DyP7V7SIDc/view?usp=sharing (start freeze in 00.06s and freeze again in 00.29s )

How can I solve it? or how to config recorder in production mode as https

ps. I'm weak english
